version: "3.7"
services:
  prisma-db:
    container_name: prisma-db
    image: postgres:12
    ports:
      - "5403:5432"
    volumes:
      - prisma-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
  prisma-test-db:
    container_name: prisma-test-db
    image: postgres:12
    ports:
      - "5402:5432"
    volumes:
      - prisma-test-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
  praha-challenge-application:
    links:
      - prisma-db
    depends_on:
      - prisma-db
    container_name: praha-challenge-application
    ports:
      - "3001:3001"
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/:/app
volumes:
  prisma-store:
    driver: local
  prisma-test-store:
    driver: local
